/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

public class App {
    public static void main(String[] args) {
        String tronscanApiKey = "default";
        Properties properties = new Properties();
        try (InputStream input = new FileInputStream("app/src/main/resources/config.properties")) {
            properties.load(input);
            tronscanApiKey = properties.getProperty("tronscanApiKey");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
